blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/KhalisFoundation/sundar-gutka-react/blob/master/README.md
    about: Please check our documentation before creating an issue.
  - name: ğŸ› Known Issues
    url: https://github.com/WahegurooNetwork/SundarGutka/issues?q=is%3Aissue+is%3Aopen+label%3Abug
    about: Check if your issue has already been reported.
